name: 'datapilot'
version: '1.0.0'
config-version: 2

profile: 'datapilot'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  datapilot:
    staging:
      +materialized: view
    marts:
      +materialized: table
      +schema: "{{ env_var('ANALYTICS_DATASET', 'datapilot_analytics') }}"
